spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: true # ???
        retry:
          enabled: true # ?????????
          max-attempts: 1 # ??????
          initial-interval: 3000 # ??????

  datasource:
    username: root
    password: dn960810
    #url?database?????????
    url: jdbc:mysql://localhost:3306/my_database?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    #    jdbc-type-for-null: null
    auto-mapping-behavior: full
  mapper-locations: classpath:com/xiaohei/rabbitmq/mapper/*.xml
  type-aliases-package: com.xiaohei.rabbitmq.entity